# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: Report a issue with the emulation (ie. graphical issue, crashes, unintended behavior with doesn't occur on hardware).
title: "Enter a title here"
labels: bug
body:
  - type: markdown
    id: md_readme
    attributes:
      value: |
        ## Important: Read First
        
        This issue tracker is for bug reports and feature requests.
        
        For tech support or questions about Cemu, [follow the links here](https://github.com/cemu-project/Cemu#links).
        
         ### Please Avoid Issues Pertaining to the Following:
         -TO DO
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: "What the bug is, in a brief decription"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "How to reprodue the issue"
    validations:
      required: true
  - type: textarea
    id: sys_info
    attributes:
      label: System Info
      description: "Place all system Info in the box below"
      placeholder: |
        Info        
        OS : Windows 10
        CPU : AMD Ryzen 5 7900X Six-Core Processor
        GPU : NVIDIA GeForce RTX 4090
        Drivers Version : 4.0.0 NVIDIA 512.95
        Cemu Version : 2.0
      value: |
        OS : 
        CPU : 
        GPU : 
        Drivers Version : 
        Cemu Version :
  - type: textarea
    id: emulation_settings
    attributes:
      label: Emulation Settings
      description: |
        Any non-default core settings.
    validations:
      required: false
  - type: textarea
    id: logs_files
    attributes:
      label: "Logs"
      description: |
        "Attach `log.txt` from your Cemu folder (*File > Open Cemu folder*)".
    validations:
      required: false
